### ISSUE TITLE
Style login page left side

### ISSUE THREAD

**Issue by azamiya** [tigerscave/ada-firebase-auth#18]
## Expected behavior
https://xd.adobe.com/view/01b0a4b3-bf90-44b1-78b1-1d60bc887fa9-7781/screen/d28dadb4-4bbf-494d-a5ea-b63a4ccae17e/login?fullscreen

**Comment by bintabaldeh** [comment]
![Screen Shot 2019-06-18 at 19 17 55](https://user-images.githubusercontent.com/47475073/59674233-d6eb2980-91fd-11e9-8d91-990981a85ac8.png)
